# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.CharField(max_length=200)),
                ('task_importance', models.CharField(choices=[('LO', 'low'), ('ST', 'standard'), ('HI', 'high')], default='ST', max_length=10)),
                ('creation_date', models.DateField(verbose_name='date added')),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
